//
//  Parameters.h
//  LogicDesign
//
//  Created by Han John on 12-4-14.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//

#ifndef LogicDesign_Parameters_h
#define LogicDesign_Parameters_h

#define INVALID -948155

#define PAPER_LOGIC_WIDTH 100      // % 10 should be 0
#define PAPER_LOGIC_HEIGHT 150     // % 10 should be 0

#define SPACE_LOGIC_WIDTH ((PAPER_LOGIC_WIDTH)/5*6)
#define SPACE_LOGIC_HEIGHT ((PAPER_LOGIC_HEIGHT)/5*6)

#define PAPER_SPACE_ADJUST_WIDTH ((PAPER_LOGIC_WIDTH)/10)
#define PAPER_SPACE_ADJUST_HEIGHT ((PAPER_LOGIC_HEIGHT)/10)

#define SCREEN_WIDTH 30.0f
#define SCREEN_HEIGHT 45.0f

#define SCREEN_WIDTH_PER_UNIT ((SCREEN_WIDTH)/(float)(SPACE_LOGIC_WIDTH))
#define SCREEN_HEIGHT_PER_UNIT ((SCREEN_HEIGHT)/(float)(SPACE_LOGIC_HEIGHT))
#define SCREEN_X_PADDING ((SCREEN_WIDTH)/12.0f)
#define SCREEN_Y_PADDING ((SCREEN_HEIGHT)/12.0f)

#define PAPER_WIDTH ((SCREEN_WIDTH)/12.0f*10.0f)
#define PAPER_HEIGHT ((SCREEN_HEIGHT)/12.0f*10.0f)
#define PAPER_LEFT_TOP_X ((-SCREEN_WIDTH)/2 + (SCREEN_X_PADDING))
#define PAPER_LEFT_TOP_Y ((SCREEN_HEIGHT)/2 - (SCREEN_Y_PADDING))

#define TPRT_ROOM 300
#define TPRT_NORMALPAPER_IGNITION 456//456
//456

#define HEAT_PER_PHLOGISTON 120.0//120
#define HEAT_SPREADRATIO_SPACE_TO_SPACE 0.15//0.06
#define HEAT_SPREADRATIO_FIRE_TO_SPACE 30.0//25.0
#define HEAT_SPREADRATIO_SPACE_TO_SPACE_DOWN 0.02 //0.02
#define HEAT_LOSSRATIO (0.000000000008)//(0.000000000008)

//25 0.02 0.08 8.5e-11

#define HEAT_CAPACITY_SPACE 1

#define TOUCH_SET_PHLOGISTON_DENSITY 1000

#define NORMALPAPER_PHLOGISTON_DENSITY 6//16
//40
#define NORMALPAPER_PHLOGISTON_CONSUMERATE 1
#define NORMALPAPER_MASS 1

#endif
